server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/txx?serverTimezone=GMT%2b8
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
mybatis:
  mapper-locations: classpath:mapper/*.xml #扫描所有mybaits的xml文件，实现mapper接口和mapper接口配置文件之间的绑定
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#将mybaits优化成为mybaits-plus，所以之前mybaits打log的配置要优化成mybaits-plus打log的配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

files:
  upload:
    path: D:/代码/txx的学习/files/

alipay:
  appId: 2021000121658445
  appPrivateKey: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDTEm3l31Pc16skMbsa7QSvpdOUfNGyk6gQCNbJK0yo67yvIJUC/pA68rhgzdSGXLx6GGExJMnAvouG+wJ/1bHJ2ztk5Qhbb9/OLiqBxYJlJtyf8A9iVLpZWe8sUxW3jHm+uSrKmgBDRcFvDzgk9YgCaHthF/0sAJTK1QcZHgY3L7YfsptY8W6IKA3ernTyGv/yN5MsCo1B6+Wr9HlJoZB34RkwDSuKQLuoC4ccyGQ8U8GoGame7YC9PTv3RvesFsiboUKxNLNLx98D+CF94hh0VbAeiGOwFbPRBhpyUf8Nz20T8G5YWxYlA3FzyyIoJziIQpKsGXc+D8bxBIzNcwFbAgMBAAECggEBAI35DXbbextG7dTQppv75XUIQ4LTWnGVpCv05hQ2TcApoKbjcZesBvO/o4lpqZQe+J/fmjBmIFbHVC6c1BeMc6PlFNROwgpO++lBYFIduhGzzB7AaHipqRbEyX20/RyTHqjNAB167MZTO0Mqp4ckqDGGecbbTe21DmBIXhfk/CVNds2DxOk9sPNpvwKNMP8wlIgO1qN+YZjes7intK/arTGeuSAb/T/WeNnCYO8e6nLWANkdOUqlzgn3+O95F0HwjjSBiDTZO7GU4BekK8YwgB25uamcpNwvNKbdcYhvHAD9aKJDhYEpQ+JLLMvRlf5x+etHm5kr1NoXO6kzdbgMOlECgYEA+mOLhgyysTShOW4D982frA6sswxEB8tvHDeyb1tAuUj2pw2tjyfZSGUlcsW2iqKy3OBKe+emh7ZmX1rBUckgwR82j8Q6AKOuFSTNQ65R0/ieWYSXLL3VPV7YAHzhYpC9YWh1CgZ4sUtetB/Ll1SUqkMGt/J0FW4P6oeETVzMudcCgYEA181T2AY6Ygc2xGMHdKZiGiX7eeOyvytKwkesIaamRGr/zQyourAtiQalZJ+7dlSfcZRJNknQUw2//63xqR7/pTgloji1456bs3m/BvWreqE4lCzAIMrOzsx75PwXZWY9RxqxKGJKnkyTnPa323qXoRcyILYAl6KzmaXv/NgXLB0CgYEArJ4F6UNFyc7ru0jyKVsz0g1H2CQDnpAMKJrpQ8XYSCRaDu7qEUA6lqNMfuR5JPhncMib8PHRp8wCpYhOsFCFaT5YgiKYjipJcEAv1pINzaGfoT08b1br9GQ3a5asVyRLuySlU2UEvc2lG260D776wqp0rknS55c6F8iXWDI63X8CgYByDpW34WLOGN37YhO4tY+4HkcRnyUEIQ98K4Fwr7HFC4BzkbNEKIWInLihvELKQeObljIzvUOcAfJuYjMNndKkMk7BtJN94ICOlVQ/i2y8faV3u0c4jbhMWItK9WowL59Hi3YC0CB8FiEWnteB6wNlIutdmpQpkNa36Jo02sk0iQKBgQDAJsdSJYKtWmFI7txH7EVOhyDoHXG/CnASQ6AfR9yp2JANvOKxqBvLw/SvBI6R51GT9jSmq9jFLrtM/EKbmV4rnIfX0Uk3Ii+ImgxV/bEady6qb7iUNd8QDc+m36QETnYjPb/HXZ3KCgluF+2mQH7wQ2sc9QjnKF7hKVN2PV7X4w==
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApn3MJmcgCZB12OeNnE6dHtJqKNR/j3ONC7eTdvid+q1czCh6FJWZ5hItaXd1zLkudPTcWMnSpzFIgHHEGmWSrpHcWa0wmPDy8x5xD5HJiSaMaPii8XbVZrJp8PCp8FzBTOU8x6HWaVPsnGPJhAseUqagMrCG5i7c4sgyGN7EHcPNK0roU+vJkD089ANhtdPCjN/psbLYclZnwRGSYNmo2l5VgcwEdDQ/ccFLir+lJLxLeORYrKER50BMNhxHoHmARY8qhDVv+Kv1A0OFs34oJL1qcqeoaJaSAYb3n0Owc00BnveW/5fD1Ks6pUE7Hptg1GDYE+DVmYzHN9I5C65PQQIDAQAB
  notifyUrl: http://ez64bw.natappfree.cc/alipay/notify


